2주차 과제 업로드합니다.
kiworkshop/java-racingcar pull request #15
Opened 2020-01-10 17:10 UTC by taesikyoo

아쉬운 부분들은
- 구현하지 못한 기능들이 있습니다.(자동차 이름이 다섯글자 이하, 자동차의  이동 시각화 등)
- commit log 요구사항대로 기능단위로 commit하지 못했습니다.(중간 중간 커밋할 때를 놓쳤습니다.)
- 기능 목록에 적은 것 외에 리팩토링하고 추상화할 요소들이 많이 보이는데 다 하지 못했습니다.
- 테스트 코드를 어떻게 짜야할지 몰라서 많이 헤맸습니다.

2020-01-15 10:56 UTC, wbluke requested changes
안녕하세요 태식 선생님!
테스트 구현 경험이 없으실텐데 고생 많으셨습니다ㅎㅎ 고생의 흔적들이 많이 보이네요.
앞으로 스터디 통해서 계속 꾸준히 연습하면 더 좋은 코드를 짜실  수 있을 겁니다.ㅎㅎ
몇 가지 코멘트 남겼는데요, 한번 보시고 모르겠는 부분은 편하게 댓글 남기거나 DM 주세요! :)

2020-01-15 10:56 UTC, wbluke commented on src/main/java/CarGame.java
>  import java.util.Scanner;
모든 파일에서 전체적으로 사용하지 않는 package들이 많이 보이는데요, 맥 기준으로 `option + cmd + L`(윈도우 : `ctrl + alt + L`) 하시면 import 정리를 전부 해줍니다. 왼쪽에 패키지명에 커서를 두고 해당 단축키를 사용하시면 해당 패키지 하위에 있는 package 정리 기능을 사용하실 수 있습니다. (코드 컨벤션도 맞춰줍니다.)

개인적으로 코드 컨벤션과 사용하지 않는 패키지 정리는 클린코드의 첫걸음이라고 생각합니다ㅎㅎ 저는 커밋 찍기 전에 매번 해당 단축키로 파일들을 정리하는 습관이 있는데요, 이번 스터디 하시면서 좋은 습관으로 가져가시면 좋을 것 같아요! :)

2020-01-15 10:56 UTC, wbluke commented on src/main/java/CarGame.java
>  import java.util.Scanner;
전체적으로 사용하지 않는 패키지들이 많이 보이는데요. 맥 기준으로 `option + cmd + L`(윈도우 : `ctrl + alt + L`)하시면 코드컨벤션도 맞춰주고 사용하지 않는 패키지들도 정리해 줍니다.
왼쪽 패키지명에 커서를 두시고 해당 단축키를 사용하시면 하위 패키지들에 대해 한방에 전부 정리해 줍니다.

개인적으로 코드 컨벤션을 맞추는 것과 사용하지 않는 패키지들을 정리하는 것은 클린 코드의 첫걸음이라고 생각합니다.ㅎㅎ 저는 커밋을 찍기 전에 늘 해당 단축키로 코드를 한번 정리하는 시간을 가지는데요, 이번 스터디를 통해 좋은 습관을 가져가시면 좋을 것 같아요 :)

2020-01-15 10:56 UTC, wbluke commented on src/main/java/main.java
> +        List<String> carNames = Arrays.asList(sc.nextLine().split(","));
```suggestion
        String inputCarName = sc.nextLine();
        String[] tokens = inputCarName.split(",");
        List<String> carNames = Arrays.asList(tokens);
```

한줄에 너무 많은 작업을 하는 것 같아요. `디미터 법칙`이라는 키워드로 한번 찾아보세요 :)

2020-01-15 10:56 UTC, wbluke commented on src/main/java/main.java
> +    public static CarGame getGameInfo() {
하나의 메소드에서 세부 private 메소드들로 쪼갤 수 있는 흐름이 보이는 것 같아요ㅎㅎ 
기능을 쪼개고 이름을 붙여서 추상화를 해보는 것은 어떨까요? :)

2020-01-15 10:56 UTC, wbluke commented on src/test/java/TestCar.java
> +        car1.setName("hyundai");
setter 사용은 최대한 지양하는 것이 좋습니다. 조금 강하게 표현하면 아예 금지된 방식이라 여기셔도 좋습니다. 
(이미 스프링을 포함한 많은 프레임워크에서는 setter를 보실 수 있지만, 적어도 내가 짠 코드에서는 setter가 없도록 하는 것이 좋습니다.)
왜 setter를 사용하면 안될까요? 한번 고민해보시면 좋을 것 같아요. :)

지금 test에서는 기본 생성자로 Car를 생성하고, 이름을 후에 세팅해주는 식으로 객체를 만들고 있는데요.
Car에 기본 생성자를 없애고, 이름으로 생성하는 생성자만 있어도 괜찮지 않을까요? :)

2020-01-15 10:56 UTC, wbluke commented on src/main/java/Car.java
> +    }
👍

2020-01-15 10:56 UTC, wbluke commented on README.md
> +    - progress를 시각화하기
👍

2020-01-15 10:56 UTC, wbluke commented on src/main/java/CarGame.java
> +    public static int generateRandomNumber() {
해당 함수는 private으로 둬도 될 것 같아요. 그리고 메소드의 순서는 public 메소드가 나온 후에, 해당 메소드 내부의 private 메소드가 차례로 나와야 합니다. 그래야 자연스럽게 읽히겠죠? ㅎㅎ
이 메소드는 아래에 있는 run() 메소드에서 사용하기 때문에 run() 메소드 아래에 위치하면 좋을 것 같아요. 
다른 메소드들도 한번 체크해보시면 좋겠네요 :)

2020-01-15 10:56 UTC, wbluke commented on src/main/java/CarGame.java
> +            if (CarGame.generateRandomNumber() >= 4) {car.forward();}
4 라는 숫자는 매직넘버네요 :) 상수로 관리하는 것이 어떨까요?

2020-01-15 10:56 UTC, wbluke commented on src/main/java/CarGame.java
>      }
run() 메소드가 두 가지 일을 하고 있는 것으로 보여요. 
1. 자동차가 진행할 것인지 판단하는 일
2. 실제로 자동차를 진행시키는 일

심지어 랜덤생성 로직이 끼어 있기 때문에 해당 메소드가 테스트 불가능한 구조인 것 같네요.ㅎㅎ
테스트 불가능한 로직을 외부로 분리하고, 해당 메소드를 테스트 가능하도록 만들 수 있을까요? :)

2020-01-15 10:56 UTC, wbluke commented on src/test/java/TestCarGame.java
> +    }
assert문을 쓰지 않고 console에 단순하게 찍어보는 테스트는 올바른 테스트 로직이 아닙니다 :)
위에 있는 테스트들도 마찬가지네요 ㅎㅎ

2020-01-15 10:56 UTC, wbluke commented on src/main/java/CarGame.java
>      }
콘솔에 결과를 출력하는 로직은 CarGame 클래스에 있기에는 해당 클래스의 역할이 너무 많은 것 같아요.
OutputView 등으로 클래스를 나누어서 책임을 분리해 보면 어떨까요?
추가로 Scanner로 입력받는 역할도 InputView 등으로 나눠볼 수 있을 것 같아요 :)

2020-01-18 01:57 UTC, taesikyoo commented on src/main/java/CarGame.java
>  import java.util.Scanner;
메일이 갈까요?

2020-01-31 12:19 UTC, woowabean approved these changes
태식 선생님~ 리뷰를 아주 잘 반영해주셨네요 💯 
온오프라인 리뷰 모두 공들여 반영해주신 것 같아 감사합니다.
일급컬렉션이나 테스트 관련해서 몇 가지 피드백 남겨드리는데요, 이번 미션은 많이 반영하셨으니 이만 approve 하고
다음 미션에서 피드백 참고하셔서 반영해보시면 좋을 것 같습니다. 수고 많으셨습니다~~!!

2020-01-31 12:19 UTC, woowabean commented on src/main/java/racingcar/domain/car/RacingCars.java
> +public class RacingCars {
오우 일급컬렉션을 적용하셨네요! 
다음 미션이나 다다음 미션쯤 일급컬렉션 피드백을 드릴까 했었는데, 저번 모임때 들으시고 바로 적용하시다니 아주 멋집니다 👍👍👍

2020-01-31 12:19 UTC, woowabean commented on src/main/java/racingcar/domain/car/RacingCars.java
> +    List<RacingCar> cars = new ArrayList<>();
요 초기화는 지금 인텔리제이에서 회색으로 표기가 되어있을텐데, 생성자에서 초기화를 해주기 때문에 다른 의도가 없으시다면 없애셔도 될거같아요ㅎㅎ

2020-01-31 12:19 UTC, woowabean commented on src/main/java/racingcar/domain/car/RacingCars.java
> +    }
일급컬렉션 내의 데이터를 가공한 값을 외부에서 사용하기 위해 해당 로직이 나온 것으로 보이는데요,
가공의 여지를 주는 stream을 외부로 던지는 것 보다, 일급컬렉션 내부에서 가공을 끝내고 결과값만 외부로 보내는 것이 좋습니다.
(객체지향의 개념에 대해서 생각해보면 이해가 가실거에요)

https://jojoldu.tistory.com/412
일급컬렉션에 대해서는 앞으로도 고민할 기회가 많을거에요. 해당 글을 레퍼런스 삼아 다음, 다다음 미션에서도 적용해보시면 좋을 것 같습니다~!

2020-01-31 12:19 UTC, woowabean commented on src/main/java/racingcar/domain/RacingCarSnapShot.java
> +    }
스냅샷 👍 

RacingCar의 상태를 보존하기 위해 해당 자동차의 데이터를 전부 꺼내서 저장하는 형식인데요,
만약 차의 필드가 정말정말 많아지면 어떻게 될까요? (이런 극단적인 사고가 설계할 때 도움이 많이 됩니다)

자동차를 그대로 카피(깊은 복사) 떠서 저장하는 방법도 있을 것 같아요ㅎㅎ

2020-01-31 12:19 UTC, woowabean commented on src/main/java/racingcar/view/OutputView.java
> +import racingcar.domain.car.RacingCar;
사용하지 않는 import 제거~

2020-01-31 12:19 UTC, woowabean commented on src/test/java/racingcar/domain/car/RacingCarTest.java
> +        assertThat(thrown).isInstanceOf(IllegalArgumentException.class);
```java
assertThrows(IllegalArgumentException.class, () -> new RacingCar("abcdef"));
```
예외 테스트는 이렇게 한번에도 할 수 있습니다 :)

2020-01-31 12:19 UTC, woowabean commented on src/main/java/racingcar/domain/proceedingstrategy/ProceedingStrategy.java
> +    public boolean isProceedable();
인터페이스에는 public 접근제어자가 무의미합니다 :)

2020-01-31 12:19 UTC, woowabean commented on src/main/java/racingcar/domain/proceedingstrategy/ManualProceedingStrategy.java
> +public class ManualProceedingStrategy implements ProceedingStrategy{
프로덕션 코드가 아닌 테스트에서만 쓰는 클래스는 테스트쪽에 두시거나, 테스트 클래스 내에서 생성해서 쓰는 것이 맞습니다ㅎㅎ
그리고 해당 전략은 굳이 클래스를 만들지 않아도 람다로 해결이 가능합니다 :)
```java
() -> true;
```

2020-01-31 12:24 UTC, wbluke approved these changes
잘못해서 회사계정으로 리뷰 남겼네요ㅠㅠ ㅋㅋ 원래 계정으로도 approve 하겠습니다

2020-02-05 23:50 UTC, merged